---
title: "About Myself"
output:
  html_document:
    code_folding: hide
    fig_width: 7
    fig_height: 6
    fig_captions: true
    theme: darkly
    highlight: default
    toc: false
    number_sections: false
---


Hello my name is Nathaniel Pyle and I am a Data Scientist. I have recently
completed a Master's of Applied Data Science at the University of Canterbury in
Christchurch New Zealand.

## Education

Master's Degree in Applied Data Science at the University of Canterbury 2024

Graduate Diploma in Applied Management from Ara's Institute of Canterbury 2019

Bachelor of Arts in English from the University of Canterbury 2016


## Personal Interests

Some of my personal interests include chess, judo and physical fitness. I enjoy
using my skills as a Data Scientist to investigate topics which interest me such
as Cancer, Wine and anything else which catches my eye.

Please feel free to have a look at my github repository [NathanielPyle](https://github.com/NathanielPyle/NathanielPyle.github.io)

## Contact Details

If you would like to contact me about my work or anything Data Science related, 
please feel free to flick me an email at nathaniel.pyle110@gmail.com or message 
me on linkedin https://www.linkedin.com/in/nathaniel-pyle-29a91a253/ .


rmarkdown::render("aboutme.rmd")
