---
title: "Projects"
output: 
  html_document:
    code_folding: hide
    fig_width: 7
    fig_height: 6
    fig_captions: true
    theme: darkly
    highlight: default
    toc: False
    number_sections: False
---

# Projects

Explore my data science projects categorised by topic and technology. 

## R Specific Projects

### [Breast Cancer Wisconsin Dataset](Breast-Cancer-Wisconsin-Dataset.html)
- **Description**: This project involved Exploratory Data Analysis (EDA) using the Breast Cancer Wisconsin (Diagnostic) dataset available from the [UC Irvine Machine Learning Repository](http://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic). 
- **Technologies**: `R`, `corrplot`, `readODS`, `dplyr`, `tidyverse`, `MASS`, `ggplot2`, and `Rtsne`

### [Portuguese Vinho Verde wine quality dataset](wine_quality.html)
- **Description**: This project involved the use of the UC Irvine Wine Dataset, available at [UC Irvine Wine Dataset](https://archive.ics.uci.edu/dataset/186/wine+quality), to explore the most important variables in determining wine quality. 
- **Technologies**: `corrplot`, `readODS`, `ISLR`, `leaps`, and `glmnet`

## Python Specific Projects

### [Palmer Penguin Dataset Visualisation](penguins_dataset_python.html)
- **Description**: This project involved the exploration fo the Palmer Penguins dataset available at
[Palmer Penguins](https://github.com/allisonhorst/palmerpenguins). The purpose of this project was to explore the body weights of penguins depending on specific conditions including: where they lived, their sex and what species they were.
- **Technologies**: `Python`, `Pandas`, `Matplotlib` and `Seaborn`

### [Titanic Dataset Visualisation](Titanic.html)
- **Description**: This project utilised the Titanic dataset available at [Titanic Kaggle](https://www.kaggle.com/c/titanic/overview) and [Data Science Dojo Github](https://github.com/datasciencedojo/datasets/blob/master/titanic.csv), to discover which variables were the most important in determining passenger survival, such as `Passenger Fare`, `Number of Siblings/Spouses Aboard` and `Age`.       
- **Technologies**: `Python`, `Pandas`, `Matplotlib`, `Numpy` and `Seaborn`


## Geospatial Specific Projects


### [Top Ten Earthquakes of 2024 and Nuclear Power Stations](earthquakes_powerplants.html)
- **Description**: This project explored regions around the world which have high volumes of earthquakes and their location to nuclear power plants. Due to data limitations, it was not possible to make a further in-depth analysis of the results. Various datasets were used in this project including the [GEM Science Tools](https://github.com/GEMScienceTools/gem-global-active-faults/tree/master/shapefile), and the [United States Geological Survey Database](https://earthquake.usgs.gov/earthquakes/search/). The full description of data sources is available in the overview section. 
- **Technologies**: `QGIS` and `Open Street Map Quick extension`.



rmarkdown::render("project.rmd")

